"""Added validation and constraints to Gamer

Revision ID: 82c632213c62
Revises: 506bde50d494
Create Date: 2025-05-30 20:30:21.178476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c632213c62'
down_revision: Union[str, None] = '506bde50d494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gamers', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('games', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'games', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='unique')
    op.alter_column('games', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('gamers', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
